# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  group: azuresecrets

pool:
  vmImage: windows-latest

steps:
- task: BicepInstall@0
  inputs:
    version: 0.12.40

